### PR TITLE
Update .editorconfig

### PR DESCRIPTION
**Pull request by KraMorK**
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11625415021 11625415021-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.104

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11626534702 11626534702-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.105

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11627872167 11627872167-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.106

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11627872167 11627872167-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.106

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11639956474 11639956474-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.108

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11640393206 11640393206-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11640433894 11640433894-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11640553034 11640553034-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.109

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11640660749 11640660749-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.110

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11640926310 11640926310-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.110

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11641161614 11641161614-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11641422772 11641422772-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.111

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11641474752 11641474752-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.111

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11641611798 11641611798-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.123

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11641682986 11641682986-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.125

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11642200044 11642200044-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.133

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11642389875 11642389875-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.136

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11641773391 11641773391-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.126

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11642450134 11642450134-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.138

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11642582212 11642582212-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.142

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11642942036 11642942036-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.147

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11643108257 11643108257-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.150

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11681608353 11681608353-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.68

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11681947719 11681947719-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.73

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11682595097 11682595097-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.85

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11682944038 11682944038-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.86

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11683547960 11683547960-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.87

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11684600665 11684600665-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.88

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11684935553 11684935553-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11685067107 11685067107-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.89

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11686958615 11686958615-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.97

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11685999070 11685999070-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.94

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by KraMorK** [comment]
/e2e/abort vsphere;Standard;containerd;1.27 11688159772 11688159772-1-con-1-27 /sys/deckhouse-oss/install:pr365-test-1 ubuntu@192.168.240.102

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/vsphere'...

**Pull request closed without merging**
