### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by KraMorK**
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Comment by KraMorK** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 10881562587 10881562587-1-con-1-27 /sys/deckhouse-oss/install:pr334-test-1

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by KraMorK** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 10881686495 10881686495-1-con-1-27 /sys/deckhouse-oss/install:pr334-test-1 ec2-user@3.65.46.190

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Comment by KraMorK** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 10883045931 10883045931-1-con-1-27 /sys/deckhouse-oss/install:pr334-test-1 ec2-user@18.197.0.232

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Comment by KraMorK** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 10884204441 10884204441-1-con-1-27 /sys/deckhouse-oss/install:pr334-test-1 ec2-user@3.76.89.218

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by KraMorK** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 10885012224 10885012224-1-con-1-27 /sys/deckhouse-oss/install:pr334-test-1 ec2-user@3.79.251.212

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/yandex-cloud'...

**Comment by KraMorK** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 10887091699 10887091699-1-con-1-27 /sys/deckhouse-oss/install:pr334-test-1

**Comment by KraMorK** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 10886445027 10886445027-1-con-1-27 /sys/deckhouse-oss/install:pr334-test-1 ec2-user@54.93.130.205

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Comment by KraMorK** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 10887484473 10887484473-1-con-1-27 /sys/deckhouse-oss/install:pr334-test-1 ec2-user@35.159.104.0

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Comment by KraMorK** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 10897786984 10897786984-1-con-1-27 /sys/deckhouse-oss/install:pr334-test-1 ec2-user@52.57.147.132

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by KraMorK** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 10897487553 10897487553-1-con-1-27 /sys/deckhouse-oss/install:pr334-test-1 ec2-user@3.73.177.156

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Pull request closed without merging**
