### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by KraMorK**
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @KraMorK. I've started the workflow for label 'e2e/run/aws'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/aws'...

**Comment by artbin** [comment]
/e2e/abort aws;WithoutNAT;containerd;1.27 11160680394 11160680394-1-con-1-27 /sys/deckhouse-oss/install:pr348-test-1 ec2-user@18.198.220.137

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by KraMorK** [comment]
/e2e/abort static;Static;containerd;1.27 11231407194 11231407194-1-con-1-27 /sys/deckhouse-oss/install:pr348-test-1 astra@192.168.199.167

**Pull request closed without merging**
